# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    App\Auth\Infrastructure\Jwt\JwtTokenValidator:
        arguments:
            $secretKey: '%env(JWT_SECRET_KEY)%'

    App\Auth\Infrastructure\Jwt\JwtTokenGenerator:
        arguments:
            $secretKey: '%env(JWT_SECRET_KEY)%'

    App\Auth\Application\TokenGeneratorInterface:
        alias: App\Auth\Infrastructure\Jwt\JwtTokenGenerator

    App\Auth\Domain\UserRepository:
        alias: App\Auth\Infrastructure\Persistence\DoctrineUserRepository

    App\Auth\Application\Query\GetMe\MeReadRepositoryInterface:
        alias: App\Auth\Infrastructure\Persistence\DoctrineMeReadRepository
    App\Auth\Infrastructure\Cookie\CookieHelper:
        arguments:
            $accessTokenTtl: '%env(int:AUTH_ACCESS_TOKEN_TTL)%'
            $refreshTokenTtl: '%env(int:AUTH_REFRESH_TOKEN_TTL)%'
            $accessCookieName: '%env(AUTH_COOKIE_NAME_ACCESS)%'
            $refreshCookieName: '%env(AUTH_COOKIE_NAME_REFRESH)%'

    App\Auth\Infrastructure\Security\JwtAuthenticator:
        arguments:
            $accessCookieName: '%env(AUTH_COOKIE_NAME_ACCESS)%'

    App\Auth\Domain\RefreshTokenRepository:
        alias: App\Auth\Infrastructure\Persistence\DoctrineRefreshTokenRepository

    App\Shared\Infrastructure\EventSubscriber\RateLimitSubscriber:
        arguments:
            $apiPublicLimiter: '@limiter.api_public'
            $apiAuthenticatedLimiter: '@limiter.api_authenticated'
            $environment: '%kernel.environment%'

when@test:
    services:
        App\Tests\Behat\FeatureContext:
            public: true
            autowire: true
        
        App\Tests\Behat\Auth\AuthContext:
            public: true
            arguments:
                $state: '@App\Tests\Behat\BehatState'
